/**
 * Example to show the usage of Eclipse IDE in generating parameterized constructor code.
 * NOTE: In the generated code, parameters of the constructor have same name as instance variables.
 * So to refer to instance variable inside constructor body, this reference is used explicitly.
 * 
 * @author Udayan Khattry
 */
package com.udayan.lecture17;

public class Point {
	public int x;
	public int y;
	//Below Constructor was generated by Eclipse IDE.
	public Point(int x, int y) {
		this.x = x;
		this.y = y;
	}
	
}
